// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVzjkOGrApUBEPPTIAldfxLuQbc4ZrsCE',
    appId: '1:666164173201:web:ef881670d63583ccdb2230',
    messagingSenderId: '666164173201',
    projectId: 'todoapp-7a5e8',
    authDomain: 'todoapp-7a5e8.firebaseapp.com',
    storageBucket: 'todoapp-7a5e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsOU0D9iSVpZQ5fgq6rBpVCQJi3xHYs3U',
    appId: '1:666164173201:android:c00c7e88a49e5519db2230',
    messagingSenderId: '666164173201',
    projectId: 'todoapp-7a5e8',
    storageBucket: 'todoapp-7a5e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIaLuVmTPvcyqzz4GAq4MDvOoXwJlZEHk',
    appId: '1:666164173201:ios:41c0cd70194aa124db2230',
    messagingSenderId: '666164173201',
    projectId: 'todoapp-7a5e8',
    storageBucket: 'todoapp-7a5e8.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIaLuVmTPvcyqzz4GAq4MDvOoXwJlZEHk',
    appId: '1:666164173201:ios:7beb64b478329384db2230',
    messagingSenderId: '666164173201',
    projectId: 'todoapp-7a5e8',
    storageBucket: 'todoapp-7a5e8.appspot.com',
    iosBundleId: 'com.example.toDoApp.RunnerTests',
  );
}
